version: '3.8'

networks:
  peloteras:
    name: peloteras
  nginx-proxy:
    name: nginx-proxy
    external: true

services:  
  peloteras-back:
    container_name: peloteras-back
    image: peloteras/backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.production
    ports:
      - '3033:3000'
    networks:
      - peloteras
      - nginx-proxy
